### ISSUE TITLE
NullPointerException on any !ba command

### ISSUE THREAD

**Issue by BegOsrs** [SkylerPIlot/Barbarians-Assault-Personal-Bests#4]
java.lang.NullPointerException: null
	at com.BaPB.BaPBPlugin.baSubmit(BaPBPlugin.java:508)
	at net.runelite.client.chat.ChatCommandManager.onChatboxInput(ChatCommandManager.java:150)
	at net.runelite.client.chat.CommandManager.handleInput(CommandManager.java:152)
	at net.runelite.client.chat.CommandManager.onScriptCallbackEvent(CommandManager.java:93)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:169)
	at client.cl(client.java:21316)
	at l.l(l.java:59576)
	at cr.c(cr.java:110)
	at client.vm(client.java:3246)
	at client.b(client.java:965)
	at al.d(al.java:344)
	at al.run(al.java:323)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by SkylerPIlot** [comment]
I am able to replicate the error when trying the commands on an account that doesn't have a personal best saved. This is caused by it trying to access a value that doesn't exist in the config file.

Will add a try-catch block next update in order to make the error message more easily diagnosable.

In the meantime try to do some runs on the account and verify you haven't signed out of runelite or changed/moved the config file.
